name: Publish static files

on:
  push:
    branches:
      - "hide_github"

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    name: 'Upload files to docs container'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload files to docs container
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'
        inlineScript: |
          storageAccountName='fsdhstaticassetstorage'
          containerName='docs'
          sourceFolder='$(Build.SourcesDirectory)'

          az storage blob upload-batch --destination $containerName --source $sourceFolder --account-name $storageAccountName --account-key $(storageAccountKey) --overwrite 
      
    - name: Post-upload Validation of Docs Blobs
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'
        inlineScript: |
          storageAccountName="fsdhstaticassetstorage"
          containerName="docs"
          blobName="_sidebar.md"
          
          echo "Checking if the blob exists..."
          exists=$(az storage blob exists --account-name $storageAccountName --container-name $containerName --name $blobName --output tsv)
          
          if [ "$exists" = "True" ]; then
            echo "Validation successful: Blob exists in container."
          else
            echo "Validation failed: Blob does not exist in container."
            exit 1
          fi

  publish_static:
    runs-on: ubuntu-latest
    name: 'Upload files to static container'
    steps:
    - name: Upload files to static container
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'
        inlineScript: |
          storageAccountName='fsdhstaticassetstorage'
          containerName='static' 
          sourceFolder='$(Build.SourcesDirectory)/static'

          az storage blob upload-batch --destination $containerName --source $sourceFolder --account-name $storageAccountName --account-key $(storageAccountKey) --overwrite 

    - name: Post-upload Validation of Static Blobs
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'
        inlineScript: |
          storageAccountName="fsdhstaticassetstorage"
          containerName="static"
          blobName="vs/ssl_cert.png"
          
          echo "Checking if the blob exists..."
          exists=$(az storage blob exists --account-name $storageAccountName --container-name $containerName --name $blobName --output tsv)
          
          if [ "$exists" = "True" ]; then
            echo "Validation successful: Blob exists in container."
          else
            echo "Validation failed: Blob does not exist in container."
            exit 1
          fi
