name: Pullrequest AI Review

permissions: read-all

on:
  pull_request: 
    types: [opened, synchronize, reopened, review_requested]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - name: Start Sysdig System Capture
      uses: gccloudone-aurora-collab/falco-actions/start@54d299d4c40de1ad6bf680fefbbfed1bc5b8f057
      with:
        mode: analyze
        sysdig-version: "sha256:c63ec30ce5db5b0d934343028031bba32b81cb7cb3f82e82d87b72c9b1694922"

    - name: Check required secrets
      run: |
        if [ -z "${{ secrets.LLM_API_KEY }}" ]; then
          echo "Error: LLM_API_KEY secret is not configured"
          exit 1
        fi

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install shippie
      run: bun i shippie

    - name: Run shippie review
      run: bun shippie review --platform=github --telemetry=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_SHA: ${{ github.sha }}
        OPENAI_API_KEY: ${{ secrets.LLM_API_KEY }}

    - name: Stop Sysdig System Capture
      uses: gccloudone-aurora-collab/falco-actions/stop@54d299d4c40de1ad6bf680fefbbfed1bc5b8f057
      with:
        mode: analyze

  audit:
    needs: scan 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Analyze
      uses: gccloudone-aurora-collab/falco-actions/analyze@54d299d4c40de1ad6bf680fefbbfed1bc5b8f057
      with:
        falco-version: 'sha256:ba05dfb209cc1c2e912ce116d230b5f59c4542e7286f05b663c499066d5d6a42'
        custom-rule-file: '.github/falco/rules/custom_rules.yaml'

